# Generated by Django 2.2.15 on 2020-08-31 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200901_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='published_date',
        ),
        migrations.AddField(
            model_name='cv',
            name='text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
