# Generated by Django 2.2.15 on 2020-09-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200901_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
